name: GitHub actions Slack Notifification
author: Rafael Karczevski <rkarczevski@gmail.com>
description: GitHub action used to send notification in slack
branding:
  icon: feather
  color: gray-dark

inputs:
  slack-webhook:
    description: "The slack webhook url"
    required: true
  github-token:
    description: "The github token used to send the notification in slack. Default is GITHUB_TOKEN env"
    required: false

runs:
  using: "node20"
  main: "index.js"
